# Generated by Django 4.2.6 on 2024-01-05 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Duty_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trooper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('REC', 'Recruit (REC)'), ('PTE', 'Private (PTE)'), ('LCP', 'Lance Corporal (LCP)'), ('CPL', 'Corporal (CPL)'), ('CFC', 'Corporal First Class (CFC)'), ('3SG', '3rd Sergeant (3SG)')], default='REC')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('stay_in', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')])),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Duty_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('duty_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.duty_date')),
                ('main_duty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.main_duty')),
                ('trooper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trooper')),
            ],
        ),
        migrations.CreateModel(
            name='Leave_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField()),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Current_Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_leaves', models.DecimalField(decimal_places=1, max_digits=5)),
                ('remarks', models.CharField(blank=True)),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.leave_type')),
                ('trooper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trooper')),
            ],
        ),
        migrations.CreateModel(
            name='Apply_Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('half_day_bool', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO')),
                ('half_day', models.DateField(blank=True, null=True)),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_leave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.current_leave')),
                ('trooper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trooper')),
            ],
        ),
        migrations.CreateModel(
            name='Additional_Duty_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night'), ('Whole', 'Whole')])),
                ('add_duty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.additional_duty')),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('duty_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.duty_date')),
                ('trooper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trooper')),
            ],
        ),
        migrations.AddConstraint(
            model_name='main_duty_time',
            constraint=models.UniqueConstraint(fields=('start_time', 'end_time', 'main_duty', 'duty_date'), name='unique_main_duty_time_per_date'),
        ),
        migrations.AddConstraint(
            model_name='leave_type',
            constraint=models.UniqueConstraint(fields=('leave_type', 'commander'), name='unique_leave_type_per_commander'),
        ),
        migrations.AddConstraint(
            model_name='current_leave',
            constraint=models.UniqueConstraint(fields=('leave_type', 'trooper', 'commander'), name='unique_leave_type_per_trooper'),
        ),
        migrations.AddConstraint(
            model_name='additional_duty_time',
            constraint=models.UniqueConstraint(fields=('trooper', 'time_of_day', 'add_duty'), name='unique_add_duty'),
        ),
    ]
