# Generated by Django 4.2.6 on 2024-01-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_additional_duty_time_unique_add_duty_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apply_leave',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_gte_start_date', violation_error_message='invalid_start_date_error'),
        ),
        migrations.AddConstraint(
            model_name='apply_leave',
            constraint=models.UniqueConstraint(fields=('start_date', 'end_date', 'trooper', 'commander'), name='unique_applied_leave', violation_error_message='duplicate_leave_error'),
        ),
    ]
