# Generated by Django 4.2.6 on 2024-01-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apply_leave_end_date_gte_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apply_leave',
            name='end_date_gte_start_date',
        ),
        migrations.RemoveConstraint(
            model_name='apply_leave',
            name='unique_applied_leave',
        ),
        migrations.RemoveField(
            model_name='trooper',
            name='stay_in',
        ),
        migrations.AddConstraint(
            model_name='apply_leave',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_gte_start_date', violation_error_message='Start date cannot be later than end date.'),
        ),
        migrations.AddConstraint(
            model_name='apply_leave',
            constraint=models.UniqueConstraint(fields=('start_date', 'end_date', 'trooper', 'commander'), name='unique_applied_leave'),
        ),
    ]
