# Generated by Django 5.0.1 on 2024-02-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_apply_leave_end_date_gte_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trooper',
            name='initial',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
